{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: netbox
  labels:
{{ include "netbox.labels" . | indent 4 }}
type: Opaque
data:
  db_password: {{ .Values.postgresql.password | b64enc | quote }}
  email_password: {{ .Values.email.password | b64enc | quote }}
  napalm_password: {{ .Values.napalm.password | b64enc | quote }}
  redis_password: {{ .Values.redis.password | b64enc | quote }}
  secret_key: {{ .Values.secretKey | default (randAscii 60) | b64enc }}
  superuser_password: {{ .Values.superuser.password | default (randAlphaNum 16) | b64enc }}
  superuser_api_token: {{ .Values.superuser.apiToken | default uuidv4 | b64enc }}
{{- end }}